# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SampleSeatGeek' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SKActivityIndicatorView', '~> 1.0.0'
  pod 'Kingfisher', '~> 6.0'

  # Pods for SampleSeatGeek

end
